name: Build and Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc make libpcap-dev

      - name: Compile Project
        run: gcc -o packet_sniffer dllsniffer-pro.c -Wall -Wextra -Werror -lpcap

      - name: Verify Binary Exists
        run: |
          if [ ! -f packet_sniffer ]; then
            echo "Linux binary not found!"
            exit 1
          fi

      - name: Rename Binary
        run: mv packet_sniffer packet_sniffer-${{ github.event.release.tag_name }}-linux

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: packet_sniffer-${{ github.event.release.tag_name }}-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
